export const PRODUCT_MOCK_DATA = {
  LIST_EMPTY: [],
  LIST_VALID: [
    {
      id: 0,
      title: "iPhone 7",
      description: "An apple mobile which is nothing like apple",
      price: 549,
      discountPercentage: 12.96,
      rating: 4.69,
      stock: 94,
      brand: "Apple",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      images: ["...", "...", "..."],
    },
    {
        id: 0,
        title: "iPhone 8",
        description: "An apple mobile which is nothing like apple",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
        images: ["...", "...", "..."],
      },
      {
        id: 0,
        title: "iPhone 9",
        description: "An apple mobile which is nothing like apple",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
        images: ["...", "...", "..."],
      },
      {
        id: 0,
        title: "iPhone 10",
        description: "An apple mobile which is nothing like apple",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
        images: ["...", "...", "..."],
      },
      {
        id: 0,
        title: "iPhone 11",
        description: "An apple mobile which is nothing like apple",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
        images: ["...", "...", "..."],
      },

  ],
};
